name: Notificar Discord
on:
  push:
    branches:
      - main
jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar mensaje a Discord
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
          COMMIT_AUTHOR: ${{ github.actor }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          COMMIT_URL: ${{ github.event.head_commit.url }}
          COMMIT_DATE: ${{ github.event.head_commit.timestamp }}
        run: |
          # Construir JSON usando jq para que sea válido
          JSON=$(jq -n \
            --arg author "$COMMIT_AUTHOR" \
            --arg message "$COMMIT_MESSAGE" \
            --arg url "$COMMIT_URL" \
            --arg date "$COMMIT_DATE" \
            '{content: "**Nuevo push por \($author)**\n**Mensaje:** \($message)\n**Fecha y hora del commit:** \($date)\n**Commit URL:** \($url)"}'
          )

          curl -H "Content-Type: application/json" \
               -X POST \
               -d "$JSON" \
               $WEBHOOK_URL
